name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: ci
  PORT: 3000
  MONGO_URI: mongodb://127.0.0.1:27017/nodejs-advanced_ci
  REDIS_URI: redis://127.0.0.1:6379
  COOKIE_KEY: ci_cookie_key
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:
  build:
    environment: ci
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.15.0']

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name: Start server
        run: |
          nohup npm run start &
      - name: Wait for server to be ready
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
            printf '.'
            sleep 5
          done
      - name: Run tests
        run: npm run test
